<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "dynamicgooglesitemap"
 *
 * Auto generated by Extension Builder 2014-02-13
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Dynamic Google Sitemap',
	'description' => 'Google Sitemap generator for dynamic pages',
	'category' => 'module',
	'author' => 'Javor Issapov',
	'author_email' => 'javor.issapov@diemedialen.de',
	'author_company' => 'Die Medialen GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.9.2',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>